version: '3.4'

services:
  jrtech.angular.docker:
    image: ${DOCKER_REGISTRY-}jrtechangulardocker
    build:
      context: .
      dockerfile: JrTech.Angular.Docker/Dockerfile
    networks:
      angular:

  jrtech.angular.app:
    image: ${DOCKER_REGISTRY-}jrtechangularapp
    build:
      context: .
      dockerfile: JrTech.Angular.Docker/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./JrTech.Angular.Docker/ClientApp:/app
    networks:
      angular:

networks:
  angular:
    